```{r}
library(tidyverse)
library(ggbeeswarm)

# Import data
station_score <- read_csv('data/processed/station_score.csv')
```

```{r}
# Density plot of priority index
station_score |> 
    ggplot(aes(x = scaled_priority_ind)) +
    geom_density() +
    geom_vline(xintercept = median(station_score$scaled_priority_ind), color = 'red') +
    geom_vline(xintercept = quantile(station_score$scaled_priority_ind, 0.25), color = 'blue') +
    geom_vline(xintercept = quantile(station_score$scaled_priority_ind, 0.75), color = 'blue') +
    labs(x = 'Priority index', y = 'Density')
```

```{r}
station_score |> 
    ggplot(aes(x = adjusted_demand, y = normal_facility_score)) +
    geom_point() +
    geom_vline(xintercept = median(station_score$adjusted_demand)) +
    geom_hline(yintercept = median(station_score$normal_facility_score))
```

```{r station-benchmark}
#Top 10 stations by facility score
top10_station <- station_score |> 
    arrange(desc(normal_facility_score)) |> 
    head(10) |> 
    select(station_name_en, area, normal_facility_score) 

bottom10_station <- station_score |> 
    arrange(normal_facility_score) |> 
    head(10) |> 
    select(station_name_en, area, normal_facility_score) 
```

```{r}
station_score |> 
    ggplot(aes(x = normal_facility_score, y = scaled_priority_ind)) + 
    geom_point()
```

```{r facility-score}
facility <- c("normal_system_accessibility","normal_hearing_impared_facility", "normal_mobility_impared_facility", "normal_visually_impaired_facility")

facility_score <- station_score |> 
    select(station_name_en, area, facility) |> 
    pivot_longer(cols = all_of(facility), names_to = "facility", values_to = "score")

facility_score |> 
    group_by(area, facility) |> 
    summarise(median_score = median(score)) |> 
    ggplot(aes(x = fct_reorder(facility, median_score), y = median_score)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    labs(x = "Facility", y = "Median score")
```

```{r}
high_priority <- station_score |> 
    filter(scaled_priority_ind > quantile(station_score$scaled_priority_ind, 0.75)) |> 
    pull(station_name_en)

facility_score |> 
    filter(station_name_en %in% high_priority) |> 
    group_by(area, facility) |> 
    summarise(median_score = median(score)) |> 
    ggplot(aes(x = fct_reorder(facility, median_score), y = median_score)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    labs(x = "Facility", y = "Median score")
```

```{r}
station_score |> 
    mutate(
        priority_cate = case_when(
            scaled_priority_ind >= quantile(scaled_priority_ind, 0.75) ~ "high",
            scaled_priority_ind < quantile(scaled_priority_ind, 0.25) ~ "low",
            TRUE ~ "medium"),
        priority_cate = factor(priority_cate, levels = c("high", "medium", "low"))) |> 
    group_by(area, priority_cate) |>
    summarise(count = n()) |> 
    ggplot(aes(x = factor(area), y = count, fill = priority_cate)) +
    geom_col(position = "fill") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    labs(x = "Area", y = "Count", fill = "Priority category")
```

```{r}
# install.packages("ggmosaic") # if needed
library(dplyr)
library(ggplot2)
library(ggmosaic)

station_score |> 
    mutate(
        priority_cate = case_when(
            scaled_priority_ind >= quantile(scaled_priority_ind, 0.75) ~ "high",
            scaled_priority_ind < quantile(scaled_priority_ind, 0.25) ~ "low",
            TRUE ~ "medium"),
        priority_cate = factor(priority_cate, levels = c("high", "medium", "low"))) |> 
  mutate(area = forcats::fct_infreq(area))

ggplot(station_score) +
  geom_mosaic(aes(x = product(area), fill = priority_cate), na.rm = TRUE) +
  labs(x = "District", y = "Share within district",
       fill = "Category") +
  theme_minimal(base_size = 12) +
  theme(panel.grid = element_blank(), 
  x = element_blank(),
  y = element_blank(),
  axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r}
library(GGally)

ggpairs(station_score, columns = facility)
```

```{r}
# box plot
station_score |> 
    mutate(scaled_priority_ind = scaled_priority_ind * 100) |>
    pivot_longer(cols = c("scaled_priority_ind", facility), names_to = "metric", values_to = "score") |>
    ggplot(aes(x = metric, y = score, fill = metric)) +
    geom_quasirandom() +
    labs(x = "Metric", y = "Score")
```
